### ISSUE TITLE
portainer stack deployment

### ISSUE THREAD

**Issue by insidecircuits** [welteki/docker_frontail_openhab#3]
I tried installing with the recommended command line but I cannot get it to work, the reason being is that I am using Portainer to manage Docker.

Further, I am trying to deploy a stack using Portainer

```
---
version: '2.2'

services:
  openhab-frontail:
    image: "welteki/frontial-openhab:latest"
    restart: always
    volumes:
      - /srv/dev-disk-by-label-HDD/appdata/openhab/userdata/logs:/var/log/openhab2:ro
    ports:
      - 9001:9001
```

And I get this:
```
Deployment error
Error response from daemon: pull access denied for welteki/frontial-openhab, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
